version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "15432:80"
    networks:
      - postgres
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
